### ISSUE TITLE
App fails to run after successful build on Ubuntu 22.04

### ISSUE THREAD

**Issue by ferrellsl** [AlynxZhou/flipclock#12]
I'm on Ubuntu 22.04 and everything builds successfully but here's the output when I run the binary:

Parsing `/usr/local/etc/flipclock.conf`.
Skip comment line.
Parsed key `ampm` and value `true`.
Skip comment line.
Skip comment line.
Parsed key `full` and value `false`.
Skip comment line.
Parsed key `show_second` and value `true`.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
Skip comment line.
argv[0]: ./flipclock
Closing old font.
Opening font from `/usr/local/share/fonts/flipclock.ttf`.
Destroying old textures.
Creating new textures with size `228x228`.
Render targets not supported by OpenGL

**Comment by AlynxZhou** [comment]
> Render targets not supported by OpenGL

Did you correctly setup your graphics driver? Or maybe you are using virtual machines without hardware acceleration?

**Comment by ferrellsl** [comment]
This is when attempting to run on real hardware.  Here's a shot of neofeth ang glxgears.
![image](https://user-images.githubusercontent.com/5926287/188320207-8253e49d-4e06-4c1d-98dd-8ccefc363ba0.png)

**Comment by AlynxZhou** [comment]
What's your SDL2 version?

**Comment by ferrellsl** [comment]
Version 2.0.20

**Comment by ferrellsl** [comment]
I can install the clock via flatpak and it runs normally so I suspect there's a problem with the SDL2 shared library location when manually building from source.

**Comment by ferrellsl** [comment]
not sure what has changed, but it builds and runs correctly now so you can close this issue.

**Comment by AlynxZhou** [comment]
> not sure what has changed, but it builds and runs correctly now so you can close this issue.

Glad to know this.
