### ISSUE TITLE
是否可以直接压缩成一个整体的SCR文件

### ISSUE THREAD

**Issue by maoxiaomo** [AlynxZhou/flipclock#13]
是否可以直接压缩成一个整体的SCR文件

**Comment by AlynxZhou** [comment]
不太行，配置文件和字体一定要带的，一定要搞成一个文件比较麻烦。

**Comment by maoxiaomo** [comment]
比如 企业管理  所有人都想要设置这个屏保  我把这个文件放在共享服务器   所有人的屏保指向flipclock.scr，客户端从本地拉取服务器文件的时候 是无法获取到文件夹内的其他文件的 所有会导致报错

**Comment by AlynxZhou** [comment]
我建议直接共享文件夹？而且每个人的配置文件可能有区别，不一定适合共享。

**Comment by maoxiaomo** [comment]
是的 我当前就是整个文件夹都进行了共享  但是选择文件的时候 只能选择一个文件  造成无法读取其他文件  报错了

**Comment by AlynxZhou** [comment]
我建议换个方案共享，让每个人都能在自己电脑上下载一份完整的，反正体积不大。或者直接给大家发压缩包。

**Comment by maoxiaomo** [comment]
我是通过AD域服务器下发的 可能不太适合 好的 感谢作者大大 我想想其他办法
