### ISSUE TITLE
Is it possible to change colors?

### ISSUE THREAD

**Issue by Therises** [AlynxZhou/flipclock#15]
Is it possible to change colors of digits and their cards?
App looks great as it is, but I would like it to look something like [this](https://i.imgur.com/o4n5gdc.png).

P.S.: I'm using your Android wrapper, which works great even on old (4.4.2) device :)

**Comment by rosoau** [comment]
I only know that under Linux the configuration file is at: /etc/flipclock.conf
Colours can be changed by un-commenting (remove #) lines 18 20 22
Then changing the hexadecimal code to something like this:
text_color = #ff4900ff
box_color = #031A15ff
background_color = #240D1Eff
The "ff" bit is added to all the codes

**Comment by AlynxZhou** [comment]
On desktop (Windows and Linux), you can achieve this via config.

On Android currently I have no idea.
