### ISSUE TITLE
Linux - unable to install due python.bytecompile error

### ISSUE THREAD

**Issue by sebastian-65** [AlynxZhou/flipclock#16]
Installation of [flipclock](https://aur.archlinux.org/packages/flipclock) package fails on Arch linux due to this Meson error:

- meson.build:8:0: ERROR: Unknown options: "python.bytecompile"

```
The Meson build system
Version: 1.1.1
Source dir: /home/sebastian/.cache/yay/flipclock/src/flipclock-2.10.0
Build dir: /home/sebastian/.cache/yay/flipclock/src/flipclock-2.10.0/build
Build type: native build

../meson.build:8:0: ERROR: Unknown options: "python.bytecompile"

A full log can be found at /home/sebastian/.cache/yay/flipclock/src/flipclock-2.10.0/build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: flipclock-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
flipclock - exit status 4
```

meson-log.txt content:

```Build started at 2023-09-03T18:55:03.331141
Main binary: /usr/bin/python
Build Options: -Db_lto=true -Db_pie=true -Dpython.bytecompile=1 -Dprefix=/usr -Dlibexecdir=lib -Dsbindir=bin -Dauto_features=enabled -Dbuildtype=plain -Dwrap_mode=nodownload
Python system: Linux
The Meson build system
Version: 1.1.1
Source dir: /home/sebastian/.cache/yay/flipclock/src/flipclock-2.10.0
Build dir: /home/sebastian/.cache/yay/flipclock/src/flipclock-2.10.0/build
Build type: native build

../meson.build:8:0: ERROR: Unknown options: "python.bytecompile"
```

**Comment by AlynxZhou** [comment]
I think that option is added by the `arch-meson` wrapper, which needs Meson 1.2.0 or higher, try update your Arch Linux first, we have 1.2.1 in the official repo.

**Comment by sebastian-65** [comment]
That would be make sense, however I've had `meson` 1.2.1-1 already installed.

**Comment by sebastian-65** [comment]
Is it possible that although meson 1.2.1-1 is indeed installed, the process of building flipclock package somehow use / require old 1.1.1 version?

- I have upgraded Arch now
- Same problem persists
- Flipclock installation works fine on my girlfriend's Arch (pretty much identical setup)

Something is wrong about my install but what could it be?

**Comment by AlynxZhou** [comment]
@sebastian-65 Try to remove your build dir and regenerate it?

**Comment by sebastian-65** [comment]
I removed `~/.cache/yay/flipclock` but to no avail. However, I tried managed to successfully install the package dodging yay and manually adding repo / signing key and installed the package via pacman.

Thank you for your help @AlynxZhou!
