### ISSUE TITLE
Windows 10多屏幕显示有问题

### ISSUE THREAD

**Issue by TonyAble** [AlynxZhou/flipclock#2]
平台 win 10 1909，笔记本外接屏幕选择扩展，显示器做主屏幕，这时显示器可以正常显示屏幕保护，但是笔记本屏幕作为扩展会显示全白。

**Comment by TonyAble** [comment]
貌似是玄学bug，不是每次都能复现。。。

**Comment by AlynxZhou** [comment]
你扩展屏幕的话感觉不是很好处理，而且我也没考虑过这种……

**Comment by TonyAble** [comment]
唔，表现有些玄学，看到win10自带的屏保有可以设置不同屏幕的，等忙完毕设折腾看看。。。

**Comment by AlynxZhou** [comment]
先别关了，有空我想想怎么实现，我现在是一点都没写这方面的代码。

**Comment by AlynxZhou** [comment]
今天写了一下多显示器相关的代码，在 Linux 下面的基本能用了，Windows 下面的我得弄一下环境，因为我换电脑了，然后看看能不能用吧。

**Comment by AlynxZhou** [comment]
![多屏](https://user-images.githubusercontent.com/8444615/102787771-949b3d80-43dc-11eb-86c6-584941c52352.jpg)

尝试最新的 release（[v2.4.0](https://github.com/AlynxZhou/flipclock/releases/download/v2.4.0/flipclock-win32.zip)），添加了多屏幕支持，每个屏幕会创建一个全屏窗口。

如果有问题再打开这个 issue 就行。
