### ISSUE TITLE
regular win32 executable?

### ISSUE THREAD

**Issue by pa-0** [AlynxZhou/flipclock#21]
First of all, thank you for sharing your work with the community.  You don't owe anyone here anything, yet you freely shared something into which you invested your time and effort -- big or small, it makes no difference.  Reading some of the issues, the entitlement I see in some people irritates me, so to bring a bit of balance to counter the lack of appreciation I've seen, I extend my own gratitude. Thank you for your contribution.

That said, I am wondering how much effort would be required to revise the source so that the project can be compiled and run as a basic win32 executable (a windowed application)?  I have some experience coding though not particularly versed in `C`.  Do you think it would be immensely difficult for me to make the appropriate modifications?

**Comment by ferrellsl** [comment]
The instructions for building a Windows binary (windowed or full screen) are right on the first page:  https://github.com/AlynxZhou/flipclock

Are you asking if it's possible to port this code to BASIC?  If so, it's rather unclear based on the lack of CAPS when you wrote "basic".

**Comment by ferrellsl** [comment]
Also forgot to mention that the Windows binary can be found here:  https://github.com/AlynxZhou/flipclock/releases/tag/v2.10.0
Just download it and modify the flipclokc.conf file for either windowed or full screen use.

**Comment by pa-0** [comment]
Much appreciated.  You covered everything I was looking for in my post - no port to BASIC intended :)
