### ISSUE TITLE
能否添加个日期？

### ISSUE THREAD

**Issue by szllw** [AlynxZhou/flipclock#4]
刚需！

**Comment by AlynxZhou** [comment]
不能

首先 fliqlo 这个常见的翻页时钟是没有日期的。

其次没什么合适的放日期的位置，也就是说会打乱布局。这个项目要考虑不同的屏幕尺寸和竖屏横屏，不太好加。

最后就是翻页时钟好看就在于界面比较简单，所以一般来说我不打算加其它的组件了。大部分使用这类屏保的用户喜欢的就是它的界面简洁对称，所以没必要加一些打破对称布局的部分。
