### ISSUE TITLE
Feature Request/Display Seconds

### ISSUE THREAD

**Issue by ferrellsl** [AlynxZhou/flipclock#6]
I love this clock.  Could you add a feature to also display the seconds?

**Comment by AlynxZhou** [comment]
No, I cannot find a proper design to place the second digits, and seconds flips too quickly, which will use more battery.

**Comment by AlynxZhou** [comment]
Should be solved by https://github.com/AlynxZhou/flipclock/commit/cd4531676987900fbb21d739d98eee545650bb6a
