### ISSUE TITLE
Show seconds

### ISSUE THREAD

**Issue by TheEightDimensions** [AlynxZhou/flipclock#7]
Can show seconds on Windows?How to config it? ^_^

**Comment by AlynxZhou** [comment]
> Can show seconds on Windows?How to config it? ^_^

No, no seconds, no suitable place for it and seconds refresh too frequently which will cost more energy on animation.

**Comment by AlynxZhou** [comment]
Should be solved by https://github.com/AlynxZhou/flipclock/commit/cd4531676987900fbb21d739d98eee545650bb6a
